name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
    - release
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Install Packege
        run:
          apt install wget

      - name: Create Environment
        run: |
          mkdir Build-AikoR
          cd Build-AikoR
          mkdir AikoR
          wget https://raw.githubusercontent.com/AikoCute-Offical/AikoR-DockerInstall/release/AikoR/aiko.yml.example -O /AikoR/aiko.yml
          wget https://raw.githubusercontent.com/AikoCute-Offical/AikoR-DockerInstall/release/AikoR/custom_inbound.json -O /AikoR/custom_inbound.json
          wget https://raw.githubusercontent.com/AikoCute-Offical/AikoR-DockerInstall/release/AikoR/custom_outbound.json -O /AikoR/custom_outbound.json
          wget https://raw.githubusercontent.com/AikoCute-Offical/AikoR-DockerInstall/release/AikoR/dns.json -O /AikoR/dns.json
          wget https://github.com/AikoCute-Offical/AikoR-DockerInstall/raw/release/AikoR/geoip.dat -O /AikoR/geoip.dat
          wget https://raw.githubusercontent.com/AikoCute-Offical/AikoR-DockerInstall/release/AikoR/geosite.dat -O /AikoR/geosite.dat
          wget https://raw.githubusercontent.com/AikoCute-Offical/AikoR-DockerInstall/release/AikoR/route.json -O /AikoR/route.json
          wget https://raw.githubusercontent.com/AikoCute-Offical/AikoR-DockerInstall/release/AikoR/rulelist -O /AikoR/AikoBlock
          wget https://raw.githubusercontent.com/AikoCute-Offical/AikoR-DockerInstall/release/docker-compose.yml -O /docker-compose.yml


      - name: Create ZIP archive
        shell: bash
        run: |
          pushd Build-AikoR || exit 1
          touch -mt $(date +%Y01010000) *
          zip -9vr ../AikoR-DockerInstall.zip .
          popd || exit 1
          FILE=./AikoR-DockerInstall.zip

      - name: Change the name
        run: |
          mv Build-AikoR AikoR-DockerInstall

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: AikoR-DockerInstall
          path: |
            ./AikoR-DockerInstall/*

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./AikoR-DockerInstall*
          tag: ${{ github.ref }}
          file_glob: true
