name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Environment
        run: |
          mkdir -p build_assets

      - name: Prepare to release
        run: |
          cp ${GITHUB_WORKSPACE}/AikoR/dns.json ./build_assets/AikoR/dns.json
          cp ${GITHUB_WORKSPACE}/AikoR/route.json ./build_assets/AikoR/route.json
          cp ${GITHUB_WORKSPACE}/AikoR/custom_outbound.json ./build_assets/AikoR/custom_outbound.json
          cp ${GITHUB_WORKSPACE}/AikoR/custom_inbound.json ./build_assets/AikoR/custom_inbound.json
          cp ${GITHUB_WORKSPACE}/AikoR/rulelist ./build_assets/AikoR/AikoBlock
          cp ${GITHUB_WORKSPACE}/AikoR/aiko.yml.example ./build_assets/AikoR/aiko.yml
          cp ${GITHUB_WORKSPACE}/docker-compose.yml ./build_assets/docker-compose.yml
      
      - name: Create ZIP archive
        shell: bash
        run: |
          pushd build_assets || exit 1
          touch -mt $(date +%Y01010000) *
          zip -9vr ../AikoR-DockerInstall.zip .
          popd || exit 1
          FILE=./AikoR-DockerInstall.zip
          DGST=$FILE.dgst
          for METHOD in {"md5","sha1","sha256","sha512"}
          do
            openssl dgst -$METHOD $FILE | sed 's/([^)]*)//g' >>$DGST
          done

      - name: Change the name
        run: |
          mv build_assets AikoR-DockerInstall

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: AikoR-$DockerInstall
          path: |
            ./AikoR-DockerInstall/*

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./AikoR-DockerInstall.zip*
          tag: ${{ github.ref }}
          file_glob: true
